# Generated by Django 2.0 on 2019-05-24 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20190523_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookauthor', models.CharField(default='神秘作家', max_length=20, verbose_name='作者')),
                ('bookcontent', models.TextField(default='神秘内容', verbose_name='内容')),
                ('bookcover', models.ImageField(upload_to='books/')),
                ('bookname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': '书',
                'verbose_name_plural': '书',
                'db_table': 'book',
            },
        ),
    ]
