# Generated by Django 2.0 on 2019-05-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_bookname'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookname',
            field=models.CharField(default='神秘书籍', max_length=20, verbose_name='书名'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_colection',
            field=models.BooleanField(default=False),
        ),
    ]
