# Generated by Django 2.0 on 2019-05-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190527_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_colection',
            new_name='is_collection',
        ),
    ]
